### ISSUE TITLE
Create kanban Board

### ISSUE THREAD

**Issue by bienvenuushindi** [pinkmoon25/Catalog-of-my-things#33]
- [Project link](https://github.com/PinkMoon25/Catalog-of-my-things/projects/1)
- Team Members: 3 people 
    - @PinkMoon25  = Team member 3
    -  @ChrispaixK  = Team member 1
    -  @bienvenuushindi  = Team member 2

**Comment by Bondok6** [comment]
# STATUS: APPROVED :green_circle: :clap: 

## Hi @bienvenuushindi , @ChrispaixK and @PinkMoon25 🙋‍♂️, 
Your kanbanboard is setup correctly!  There is nothing else to say other than... Great job 👏 

## Highlights
- Link to their GitHub project ✅
- Information about the number of people in their group ✅
- Create card with the number of points in the \[Xpt\] ✅
- All tasks added successfully ✅

HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />

Cheers and Happy coding!👏👏👏

**Comment by pinkmoon25** [comment]
Thank you @Bondok6 for the review :+1:
